In [1]:
import torch

In [2]:
# torch.cat(tensors, dim=0, out=None)
t = torch.ones((2, 3))
t_0 = torch.cat([t, t], dim=0)
t_1 = torch.cat([t, t], dim=1)
print("t_0:{} shape:{}\nt_1:{} shape;{}".format(t_0, t_0.shape, t_1, t_1.shape))

t_0:tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) shape:torch.Size([4, 3])
t_1:tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]) shape;torch.Size([2, 6])


In [3]:
# torch.stack(tensors, dim=0, out=None)
t = torch.ones((2, 3))
# dim =2
t_stack2 = torch.stack([t, t, t], dim=2)
print('\nt_stack2.shape:{}'.format(t_stack2.shape))
# dim =0
t_stack0 = torch.stack([t, t, t], dim=0)
print("\nt_stack0.shape:{}".format(t_stack0.shape))
t, t_stack2, t_stack0
# dim =1
t_stack1 = torch.stack([t, t, t, t], dim=1)
print('\nt_stack1.shape;{}'.format(t_stack1.shape))


t_stack2.shape:torch.Size([2, 3, 3])

t_stack0.shape:torch.Size([3, 2, 3])

t_stack1.shape;torch.Size([2, 4, 3])


In [4]:
# torch.chunk(input, chunks, dim=0)
a = torch.ones((2, 7))  # 7
list_of_tensors = torch.chunk(a, dim=1, chunks=3)  # 3
for idx, t in enumerate(list_of_tensors):
    print("第{}个张量：{}, shape is {}".format(idx+1, t, t.shape))

第1个张量：tensor([[1., 1., 1.],
        [1., 1., 1.]]), shape is torch.Size([2, 3])
第2个张量：tensor([[1., 1., 1.],
        [1., 1., 1.]]), shape is torch.Size([2, 3])
第3个张量：tensor([[1.],
        [1.]]), shape is torch.Size([2, 1])


In [5]:
# torch.split(tensor, split_size_or_sections, dim=0)
t = torch.ones((2, 5))
list_of_tensors = torch.split(t, [2, 1, 2], dim=1)
for idx, t in enumerate(list_of_tensors):
    print("第{}个张量：{}, shape is {}".format(idx+1, t, t.shape))

第1个张量：tensor([[1., 1.],
        [1., 1.]]), shape is torch.Size([2, 2])
第2个张量：tensor([[1.],
        [1.]]), shape is torch.Size([2, 1])
第3个张量：tensor([[1., 1.],
        [1., 1.]]), shape is torch.Size([2, 2])


In [6]:
# torch.index_select(input, dim, index, out=None)
# 创建均匀分布
t = torch.randint(0, 9, size=(3, 3))
# 注意 idx 的 dtype 不能指定为 torch.float
idx = torch.tensor([0, 2], dtype=torch.long)
# 取出第0行和第2行
t_select = torch.index_select(t, dim=0, index=idx)
print("t:\n{}\nt_select:\n{}".format(t, t_select))

t:
tensor([[8, 4, 1],
        [3, 5, 2],
        [1, 0, 4]])
t_select:
tensor([[8, 4, 1],
        [1, 0, 4]])


In [7]:
# torch.masked_select(input, mask, out=None)
t = torch.randint(0, 9, size=(3, 3))
mask = t.lt(5)  # ge is mean greater than or equal/    gt: greater than le lt
# 取出大于5的数
t_select = torch.masked_select(t, mask)
print("t:\n{}\nmask:{}\nt_select:\n{}".format(t, mask, t_select))

t:
tensor([[5, 2, 6],
        [8, 1, 4],
        [2, 4, 7]])
mask:tensor([[False,  True, False],
        [False,  True,  True],
        [ True,  True, False]])
t_select:
tensor([2, 1, 4, 2, 4])


In [8]:
# torch.reshape(input, shape)
# 生成 0 到 8 的随机排列
t = torch.randperm(8)
# -1 表示这个维度是根据其他维度计算的出
t_reshape = torch.reshape(t, (-1, 2, 2))
print("t:{}\nt_reshape:{}\nt.shape:{}\nt_reshape:{}".format(t, t_reshape, t.shape, t_reshape.shape))

t:tensor([5, 1, 2, 4, 3, 6, 7, 0])
t_reshape:tensor([[[5, 1],
         [2, 4]],

        [[3, 6],
         [7, 0]]])
t.shape:torch.Size([8])
t_reshape:torch.Size([2, 2, 2])


In [9]:
# 修改张量 t 的第 0 个元素，张量 t_reshape 也会被改变
t[0] = 1024
print("t:{}\nt_reshape:\n{}".format(t, t_reshape))
print("t.data 内存地址:{}".format(id(t.data)))
print("t_reshape.data 内存地址:{}".format(id(t_reshape.data)))

t:tensor([1024,    1,    2,    4,    3,    6,    7,    0])
t_reshape:
tensor([[[1024,    1],
         [   2,    4]],

        [[   3,    6],
         [   7,    0]]])
t.data 内存地址:4598748800
t_reshape.data 内存地址:4598748800


In [10]:
# torch.transpose(input, dim0, dim1)
# 把 c*h*w 变换为 h*w*c
t = torch.rand((2, 3, 4))
t_transpose = torch.transpose(t, dim0=1, dim1=2)# c*h*w     c*h*w
print("t shape: {}\nt_transpose shape: {}".format(t.shape, t_transpose.shape))

t shape: torch.Size([2, 3, 4])
t_transpose shape: torch.Size([2, 4, 3])


In [11]:
# torch.squeeze(input, dim=None, out=None)
# 维度 0 和 3 的长度时 1
t = torch.rand((1, 2, 3, 1))
# 可以移除维度 0 和 3
t_sq = torch.squeeze(t)
# 可以移除维度 0
t_0 = torch.squeeze(t, dim=0)
# 不能移除 1
t_1 = torch.squeeze(t, dim=1)
print("t.shape: {}".format(t.shape))
print("t_sq.shape: {}".format(t_sq.shape))
print("t_0.shape: {}".format(t_0.shape))
print("t_1.shape: {}".format(t_1.shape))

t.shape: torch.Size([1, 2, 3, 1])
t_sq.shape: torch.Size([2, 3])
t_0.shape: torch.Size([2, 3, 1])
t_1.shape: torch.Size([1, 2, 3, 1])


In [12]:
# torch.add(input, other, out=None)
# torch.add(input, other, *, alpha=1, out=None)
# torch.addcdiv(input, tensor1, tensor2, *, value=1, out=None)
# torch.addcmul(input, tensor1, tensor2, *, value=1, out=None)